create schema if not exists ESTUDO_CASO2;

use ESTUDO_CASO2;

create table if not exists PASSAGEIROS(
PASS_CPF VARCHAR(11) primary key,
PASS_NOME VARCHAR(45) NOT NULL,
PASS_RUA VARCHAR(45) NOT NULL,
PASS_NUMRUA INT NOT NULL,
PASS_BAIRRO VARCHAR(45) NOT NULL,
PASS_CIDADE VARCHAR(45) NOT NULL,
PASS_ESTADO VARCHAR(45) NOT NULL,
PASS_PAIS VARCHAR(45) NOT NULL,
PASS_CODPOSTAL VARCHAR(45) NOT NULL,
PASS_TELEFONE VARCHAR(45) NOT NULL,
PASS_EMAIL VARCHAR(100) NOT NULL
);

create table if not exists AEROPORTOS(
AEROP_COD INT primary key,
AEROP_NOME VARCHAR(50) NOT NULL,
AEROP_CIDADE VARCHAR(45) NOT NULL,
AEROP_PAIS VARCHAR(45) NULL,
AEROP_LATITUDE FLOAT NOT NULL,
AEROP_LONGITUDE FLOAT NOT NULL
);

create table if not exists AERONAVES(
AERON_PREFIXO INT primary key,
AERON_MODELO VARCHAR(30) NOT NULL,
AERON_FABRICANTE VARCHAR(50) NOT NULL,
AERON_ANOFABR DATE NOT NULL,
AERON_CAPACIDADE DECIMAL (10,3) NOT NULL,
AERON_AUTONOMIA TEXT NOT NULL
);

create table if not exists FUNCIONARIOS(
FUNC_ID INT primary key,
FUNC_NOME VARCHAR(45) NOT NULL,
FUNC_RUA VARCHAR(45) NOT NULL,
FUNC_NUMRUA INT NOT NULL,
FUNC_BAIRRO VARCHAR(45) NOT NULL,
FUNC_CIDADE VARCHAR(45) NOT NULL,
FUNC_ESTADO VARCHAR(45) NOT NULL,
FUNC_PAIS VARCHAR(45) NOT NULL,
FUNC_CODPOSTAL VARCHAR(45) NOT NULL,
FUNC_TELEFONE VARCHAR(45) NOT NULL,
FUNC_EMAIL VARCHAR(100) NOT NULL,
FUNC_CPF VARCHAR(11) NOT NULL,
FUNC_FUNCAO TEXT NOT NULL,
FUNC_DATANASC DATE NOT NULL
);

create table if not exists VOOS(
VOO_COD INT,
VOO_DATA DATE NOT NULL,
VOO_HORA TIME NOT NULL,
VOO_AEROP_ORIGEM INT,
VOO_AEROP_DESTINO INT,
VOO_AERON INT,
primary key (VOO_COD, VOO_AEROP_ORIGEM, VOO_AEROP_DESTINO, VOO_AERON),
constraint FK_AERONAVES foreign key (VOO_AERON) 
references AERONAVES(AERON_PREFIXO),
constraint FK_AEROPORTOS foreign key (VOO_AEROP_ORIGEM)
references AEROPORTOS(AEROP_COD),
constraint FK_AEROPORTOS_DESTINO foreign key (VOO_AEROP_DESTINO)
references AEROPORTOS(AEROP_COD)
);


create table if not exists RESERVAS(
RESER_COD INT,
RESER_VOO INT,
RESER_PASS VARCHAR(11),
primary key (RESER_COD, RESER_VOO, RESER_PASS),
constraint FK_VOOS foreign key (RESER_VOO) 
references VOOS(VOO_COD),
constraint FK_PASSAGEIROS foreign key (RESER_PASS)
references PASSAGEIROS(PASS_CPF)
);

create table if not exists FUNCIONARIOS_VOOS(
FCVO_FUNCIONARIOS INT,
FCVO_VOOS INT,
primary key(FCVO_FUNCIONARIOS,FCVO_VOOS),
constraint FCVO_PKFK_FUNCIONARIOS foreign key(FCVO_FUNCIONARIOS) references FUNCIONARIOS(FUNC_ID),
constraint FCVO_PKFK_VOOS foreign key(FCVO_VOOS) references VOOS(VOO_COD)
);

#Exemplo de Alters
ALTER TABLE PASSAGEIROS ADD ABC INT;
ALTER TABLE PASSAGEIROS MODIFY COLUMN ABC VARCHAR(10);
ALTER TABLE PASSAGEIROS CHANGE COLUMN ABC ABCD VARCHAR(10);
ALTER TABLE PASSAGEIROS DROP COLUMN ABCD;
ALTER TABLE AEROPORTOS ADD ABC INT;
ALTER TABLE AEROPORTOS MODIFY COLUMN ABC VARCHAR(10);
ALTER TABLE AEROPORTOS CHANGE COLUMN ABC ABCD VARCHAR(10);
ALTER TABLE AEROPORTOS DROP COLUMN ABCD;
ALTER TABLE AERONAVES ADD ABC INT;
ALTER TABLE AERONAVES MODIFY COLUMN ABC VARCHAR(10);
ALTER TABLE AERONAVES CHANGE COLUMN ABC ABCD VARCHAR(10);
ALTER TABLE AERONAVES DROP COLUMN ABCD;
ALTER TABLE FUNCIONARIOS ADD ABC INT;
ALTER TABLE FUNCIONARIOS MODIFY COLUMN ABC VARCHAR(10);
ALTER TABLE FUNCIONARIOS CHANGE COLUMN ABC ABCD VARCHAR(10);
ALTER TABLE FUNCIONARIOS DROP COLUMN ABCD;
ALTER TABLE VOOS ADD ABC INT;
ALTER TABLE VOOS MODIFY COLUMN ABC VARCHAR(10);
ALTER TABLE VOOS CHANGE COLUMN ABC ABCD VARCHAR(10);
ALTER TABLE VOOS DROP COLUMN ABCD;
ALTER TABLE RESERVAS ADD ABC INT;
ALTER TABLE RESERVAS MODIFY COLUMN ABC VARCHAR(10);
ALTER TABLE RESERVAS CHANGE COLUMN ABC ABCD VARCHAR(10);
ALTER TABLE RESERVAS DROP COLUMN ABCD;
ALTER TABLE FUNCIONARIOS_VOOS ADD ABC INT;
ALTER TABLE FUNCIONARIOS_VOOS MODIFY COLUMN ABC VARCHAR(10);
ALTER TABLE FUNCIONARIOS_VOOS CHANGE COLUMN ABC ABCD VARCHAR(10);
ALTER TABLE FUNCIONARIOS_VOOS DROP COLUMN ABCD;

#Exemplo de drop
create table if not exists ABC(
A INT primary key
);
drop table ABC
